name: Compile Goo Engine


on:
  push:
    branches: [ "goo-engine-main" ]
  pull_request:
    branches: [ "goo-engine-main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: 'true'

      - name: Subversion install
        run: choco install svn -y

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: clone others
        run: cd ${{ github.workspace }}/lib ; git clone https://projects.blender.org/blender/lib-windows_x64.git windows_x64 ; cd ${{ github.workspace }}

        
      - name: Make make
        run: ./make
        
