name: Compile Goo Engine

on:
  workflow_dispatch:
    inputs:
      operating_system:
        description: "OS: <Windows/Linux>"
        required: true
        options: 
          - Windows
          - Linux
  push:
    branches: [ "goo-engine-main" ]
  pull_request:
    branches: [ "goo-engine-main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: 'true'

      - name: Install Subversion
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install svn -y

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Build project
        run: ./make  # Replace with your actual build command

      - name: Zip Release Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: 7z a -r release.zip ../build_windows_x64_vc17_Release/bin/Release/*
        
      - name: Zip Release Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: 7z a -r release.zip ../build_linux_x64_gcc_Release/bin/Release/*


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.sha }}-${{ github.run_number }}
          name: v${{ github.sha }}-${{ github.run_number }}
          files: release.zip
          draft: true
