name: Compile Goo Engine

on:
  workflow_dispatch:
    inputs:
      operating_system:
        description: "OS: <Windows/Linux> | Leave blank for both"
        required: false
        default: Windows
        options: 
          - Windows
          - Linux
      branch:
        description: "Branch to checkout from dillongoostudios/goo-engine"
        required: false
  push:
    branches: [ "goo-engine-v4.1-release" ]
  pull_request:
    branches: [ "goo-engine-v4.1-release" ]

jobs:
  build-windows:
    runs-on: windows-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.operating_system == 'Windows' || github.event.inputs.operating_system == '' }}

    steps:
      - name: Checkout repository
        if: ${{ github.event_name != 'workflow_dispatch' || !github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: 'true'

      - name: Checkout dillongoostudios/goo-engine
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          repository: dillongoostudios/goo-engine
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
          lfs: 'true'

      - name: Install Subversion
        run: choco install svn -y

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Build project
        run: echo "y" | ./make  # Replace with your actual build command



      - name: Upload Windows release artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: ../build_windows_x64_vc17_Release/bin/Release/*

  build-linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.operating_system == 'Linux' || github.event.inputs.operating_system == ''}}

    steps:
      - name: Checkout repository
        if: ${{ github.event_name != 'workflow_dispatch' || !github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: 'true'

      - name: Checkout dillongoostudios/goo-engine
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch }}
        uses: actions/checkout@v4
        with:
          repository: dillongoostudios/goo-engine
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
          lfs: 'true'

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install build-essential git git-lfs subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
          sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
          ./build_files/utils/make_update.py --use-linux-libraries

      - name: Build project
        run: |
          echo "y" | make update
          echo "y" | make  # Replace with your actual build command

      - name: Tar release
        run: tar -czvf linux-release.tar.gz -C ../build_linux/bin/* .

      - name: Upload Linux release artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: linux-release.tar.gz
