name: Compile Goo Engine


on:
  push:
    branches: [ "goo-engine-main" ]
  pull_request:
    branches: [ "goo-engine-main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: 'true'

      - name: Subversion install
        run: choco install svn -y

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Make
        run: ./make.bat
      - name: SVN cleanup
        run: cd lib ; svn cleanup ; svn update
      - name: Make
        run: ./make.bat
        
